### ISSUE TITLE
How to install but also keep up to date with the dev updates

### ISSUE THREAD

**Issue by electron271** [4ms/4ms-kicad-script#5]
As I try to contribute to these repos, and also want the latest plugins always, how do I get KiCAD to read the plugins but also easily pull new updates from git?

**Comment by electron271** [comment]
I tried the normal install, but it only worked for the faceplate generator, and only partly

**Comment by danngreen** [comment]
I symlink the action plugin files into the Kicad 6 plug-in dir. Something like this does the trick:
```
ln -s /full/path/to/4ms-kicad-script/makefp/kicad-6-plugin/* /full/path/to/KiCad/6.0/scripting/plugins/
```

Also, keep in mind you have to copy the `faceplate_footprint_lib_TEMPLATE.py` file, rename it `faceplate_footprint_lib.py`, and then edit the new file with the path to your `4ms_Faceplate.pretty` library

**Comment by electron271** [comment]
I'm on windows, but there is something similar, I'll close this issue once I test it. (I do plan to dual-boot)

**Comment by danngreen** [comment]
1. I customized some of the colors from the Nord theme so it looked good on my screen. I use different colors for my different computers since the screens are different. And I often change the opacity and sometimes the colors as I work, depending on what layers I want to highlight at the moment.
2. Mostly macOS
3. Not sure what you mean... software for what?
4. We use the PJ398SM jacks from WQP, which I think might be the same ones Thonk sells (I'm not sure, though, you'd have to ask Thonk). For using with a breadboard, my tip is to solder wires to the jack and then stick the wires in the breadboard. Use solid wire, not stranded. Another tip is to use an old faceplate and mount the jacks to that. Then you can keep all your jacks together, and if the wires are long enough, you can even mount the faceplate to a case.

**Comment by electron271** [comment]
I mean software to make synthesizers (I'll work on stuff in a little)

**Comment by electron271** [comment]
Also, where do you buy the jacks? I would buy some more jacks, but the shipping is ridiculous

**Comment by electron271** [comment]
@danngreen I'm going to do the symlinks right now

**Comment by electron271** [comment]
I live pretty close to ModularAddict, so I'll see if maybe I can order from them (when they have it in stock)

**Comment by electron271** [comment]
Alright, I'm on windows, so heres the command for anyone else who might want it (maybe put in the README?)
`mklink /full/path/to/4ms-kicad-script/makefp/kicad-6-plugin/* /full/path/to/KiCad/6.0/scripting/plugins/`
RUN WITH ADMIN

**Comment by danngreen** [comment]
Thanks for that. I updated the makefp README in 5e4ea21cd21d7417ba989ff5b3ee70eff6e00ad6

**Comment by danngreen** [comment]
OK to close this issue?

**Comment by electron271** [comment]
Yes, but actually revert that, windows has a lot of problems with symlinks that makes that command not work @danngreen

**Comment by danngreen** [comment]
Ah ok. I'll remove it.

**Comment by electron271** [comment]
I think that maybe there should be a bash and batch script for making all of the symlinks?

**Comment by electron271** [comment]
I'm on linux, so I'm testing it right now
